In [1]:
!pip install nptyping beartype

   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
    --------------------------------------- 10.2/819.1 kB ? eta -:--:--
   - ------------------------------------- 30.7/819.1 kB 660.6 kB/s eta 0:00:02
   - ------------------------------------- 41.0/819.1 kB 487.6 kB/s eta 0:00:02
   -- ------------------------------------ 61.4/819.1 kB 544.7 kB/s eta 0:00:02
   ---- ---------------------------------- 92.2/819.1 kB 476.3 kB/s eta 0:00:02
   ----- -------------------------------- 112.6/819.1 kB 504.4 kB/s eta 0:00:02
   ------ ------------------------------- 143.4/819.1 kB 500.5 kB/s eta 0:00:02
   -------- ----------------------------- 174.1/819.1 kB 499.5 kB/s eta 0:00:02
   --------- ---------------------------- 194.6/819.1 kB 535.8 kB/s eta 0:00:02
   ---------- --------------------------- 225.3/819.1 kB 529.7 kB/s eta 0:00:02
   ----------- -------------------------- 256.0/819.1 kB 542.5 kB/s eta 0:00:02
   ------------ ------------------------- 276.5/819.1 kB 

In [6]:
import numpy as np

data: list[list[int]] = [[0, 1, 2, 3],
                        [4, 5, 6, 7],
                        [8, 9, 10, 11]]

arr: np.ndarray = np.array(data)

print(arr)
print(f"Shape of Object {arr.shape}")  # 3 rows and 4 columns
print(arr.dtype)
print(f"Number of Dimensions {arr.ndim}")  # 2 dimensional array
print(f"Total Items in array {arr.size}")  # Total elements in array
print(arr.itemsize)  # each item size

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape of Object (3, 4)
int32
Number of Dimensions 2
Total Items in array 12
4


In [7]:
import numpy as np

data:np.ndarray=np.arange(1,11)

print(data)
print(data+5)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


### Compare numpy vs traditional method

In [20]:
import numpy as np
import time
start_time=time.time()
data:np.ndarray=np.arange(1,10000000)
data+5
end_time=time.time()

elapsed_time=end_time-start_time
print(elapsed_time)


0.04847884178161621


In [22]:
start_time=time.time()
data:list[int]=list(range(1,10000000))

[i+5 for i in data]
end_time=time.time()
elapsed_time=end_time-start_time
print(elapsed_time)

2.7003087997436523


In [23]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5:11] = 1000 # normal python list that perform task is not possible except numpy
print(data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [26]:
import numpy as np

data:np.ndarray=np.arange(1,21)
print(data)
print(data[5:11])
data[5:11]=1000
print(data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


In [27]:
import numpy as np

data:np.ndarray=np.array([1,2,3,4,5])
print(data)
data1:np.ndarray=np.array([True,False,False,True,True])
print(data[data1])     # Return those index values which are true


[1 2 3 4 5]
[1 4 5]


In [28]:
import numpy as np

data:np.ndarray=np.array([1,2,3,4,5])
print(data)
print(data[data%2==0])         # Return those index values which are even/true 

[1 2 3 4 5]
[2 4]


In [31]:
print(data)
#       Value which wanna search              where we search
print(np.in1d(3,                                    data))  # return value in boolean

print(np.intersect1d(3,data))   # return intersection value

[1 2 3 4 5]
[ True]
[3]


In [32]:
x : np.ndarray = np.array([1,3,4,5,7])
y : np.ndarray = np.array([6,3,2,5,100])

display(x)
display(y)
np.where(x > y, x, y)  # check both arrrays an return where value is maximum

array([1, 3, 4, 5, 7])

array([  6,   3,   2,   5, 100])

array([  6,   3,   4,   5, 100])

# Create Numpy arrays

In [33]:
a : np.ndarray = np.arange(3*3).reshape(3,3)
print(a)
a : np.ndarray = np.arange(5*3).reshape(5,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [34]:
a : np.ndarray = np.arange(2*3*3).reshape(2,3,3)
print(a)
print('=======')
a : np.ndarray = np.arange(5*2*2).reshape(5,2,2)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [37]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [38]:
a : np.ndarray = np.arange(5*2*2).reshape(5,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [39]:
np.ones_like(a)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [40]:
ndata : np.ndarray = np.arange(1,21)

print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax())  # return maximum value index number
print(ndata.argmin)
print(ndata.mean())
print(ndata.std())  # std means standard deviation
print(ndata.sum())
print(ndata.cumsum())   # cummulative sum

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
19
<built-in method argmin of numpy.ndarray object at 0x00000206FDB03C90>
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
